// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Simulation snapshots: serializable state sent from sim thread to game thread.

use symtropy_consciousness_physics::macro_bridge::MacroWorldModifiers;

/// Snapshot of the simulation state at a given tick.
///
/// Sent from the sim thread to the game thread via channel.
/// Must be cheap to clone (no large allocations).
#[derive(Debug, Clone)]
pub struct SimSnapshot {
    /// Simulation tick this snapshot represents.
    pub tick: u64,
    /// Governance summary.
    pub governance: GovernanceSummary,
    /// Economy summary.
    pub economy: EconomySummary,
    /// Faction summaries.
    pub factions: Vec<FactionSummary>,
    /// Events generated this tick.
    pub events: Vec<SimEvent>,
}

/// Compact governance state for cross-thread transport.
#[derive(Debug, Clone, Default)]
pub struct GovernanceSummary {
    pub stability: f64,
    pub oppression_index: f64,
    pub emergency_active: bool,
    pub veto_count: u32,
    pub override_count: u32,
    pub authority_level: String,
}

/// Compact economy state for cross-thread transport.
#[derive(Debug, Clone, Default)]
pub struct EconomySummary {
    pub gini: f64,
    pub total_production: f64,
    pub currency_supply: f64,
}

/// Compact faction state for cross-thread transport.
#[derive(Debug, Clone)]
pub struct FactionSummary {
    pub name: String,
    pub ideology: [f64; 4],
    pub population_fraction: f64,
    pub in_conflict: bool,
}

/// Events generated by the simulation, sent to the game thread.
#[derive(Debug, Clone)]
pub enum SimEvent {
    /// A governance proposal was created.
    ProposalCreated { description: String, tier: u8 },
    /// A proposal passed or failed.
    ProposalResolved { description: String, passed: bool },
    /// A veto was exercised.
    VetoExercised { by: String },
    /// An economic crisis occurred.
    EconomicCrisis { severity: f64 },
    /// A faction conflict started.
    FactionConflict {
        faction_a: String,
        faction_b: String,
    },
    /// A natural disaster or emergency.
    Emergency { description: String, severity: f64 },
    /// Epoch milestone reached.
    EpochMilestone { epoch: u32, description: String },
    /// Generic text event for the game log.
    Log(String),
}

/// Actions the player can send from the game thread to the sim thread.
#[derive(Debug, Clone)]
pub enum PlayerAction {
    /// Cast a vote on the current proposal.
    CastVote {
        agent_name: String,
        phi: f64,
        approve: bool,
    },
    /// Exercise a guardian veto.
    Veto { agent_name: String, phi: f64 },
    /// Execute a TEND exchange.
    TendExchange {
        from: String,
        to: String,
        amount: f64,
    },
    /// Set governance policy.
    SetPolicy { key: String, value: f64 },
    /// Set simulation speed.
    SetSpeed(f64),
    /// Toggle pause.
    TogglePause,
}

impl SimSnapshot {
    /// Create an empty initial snapshot.
    pub fn initial() -> Self {
        Self {
            tick: 0,
            governance: GovernanceSummary::default(),
            economy: EconomySummary::default(),
            factions: Vec::new(),
            events: Vec::new(),
        }
    }

    /// Convert this snapshot to [`MacroWorldModifiers`] for the physics engine.
    ///
    /// `production_baseline` is the expected total production at equilibrium —
    /// used to normalize `total_production` to [0, 1]. Pass `1000.0` if unknown.
    ///
    /// `faction_harmony_bias` should be computed from your faction ideology vectors
    /// (e.g., mean of the harmony dimension across all factions weighted by population).
    /// Pass `0.0` if you don't have faction data.
    pub fn to_macro_modifiers(
        &self,
        production_baseline: f64,
        faction_harmony_bias: f64,
    ) -> MacroWorldModifiers {
        let production_norm = if production_baseline > 0.0 {
            (self.economy.total_production / production_baseline).clamp(0.0, 1.0)
        } else {
            0.5
        };
        MacroWorldModifiers::from_sim(
            self.governance.stability,
            self.governance.oppression_index,
            self.economy.gini,
            self.governance.emergency_active,
            production_norm,
            faction_harmony_bias,
        )
    }
}

/// Linearly interpolate between two snapshots.
pub fn interpolate_snapshots(a: &SimSnapshot, b: &SimSnapshot, t: f64) -> SimSnapshot {
    let t = t.clamp(0.0, 1.0);
    SimSnapshot {
        tick: if t < 0.5 { a.tick } else { b.tick },
        governance: GovernanceSummary {
            stability: lerp(a.governance.stability, b.governance.stability, t),
            oppression_index: lerp(
                a.governance.oppression_index,
                b.governance.oppression_index,
                t,
            ),
            emergency_active: if t < 0.5 {
                a.governance.emergency_active
            } else {
                b.governance.emergency_active
            },
            veto_count: if t < 0.5 {
                a.governance.veto_count
            } else {
                b.governance.veto_count
            },
            override_count: if t < 0.5 {
                a.governance.override_count
            } else {
                b.governance.override_count
            },
            authority_level: if t < 0.5 {
                a.governance.authority_level.clone()
            } else {
                b.governance.authority_level.clone()
            },
        },
        economy: EconomySummary {
            gini: lerp(a.economy.gini, b.economy.gini, t),
            total_production: lerp(a.economy.total_production, b.economy.total_production, t),
            currency_supply: lerp(a.economy.currency_supply, b.economy.currency_supply, t),
        },
        factions: if t < 0.5 {
            a.factions.clone()
        } else {
            b.factions.clone()
        },
        events: Vec::new(), // Events are discrete, not interpolated
    }
}

fn lerp(a: f64, b: f64, t: f64) -> f64 {
    a * (1.0 - t) + b * t
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn initial_snapshot() {
        let snap = SimSnapshot::initial();
        assert_eq!(snap.tick, 0);
        assert!(snap.events.is_empty());
    }

    #[test]
    fn interpolate_midpoint() {
        let a = SimSnapshot {
            tick: 10,
            governance: GovernanceSummary {
                stability: 0.8,
                oppression_index: 0.2,
                ..Default::default()
            },
            economy: EconomySummary {
                gini: 0.3,
                total_production: 100.0,
                currency_supply: 1000.0,
            },
            factions: Vec::new(),
            events: Vec::new(),
        };
        let b = SimSnapshot {
            tick: 11,
            governance: GovernanceSummary {
                stability: 0.6,
                oppression_index: 0.4,
                ..Default::default()
            },
            economy: EconomySummary {
                gini: 0.5,
                total_production: 200.0,
                currency_supply: 900.0,
            },
            factions: Vec::new(),
            events: Vec::new(),
        };

        let mid = interpolate_snapshots(&a, &b, 0.5);
        assert!((mid.governance.stability - 0.7).abs() < 1e-10);
        assert!((mid.governance.oppression_index - 0.3).abs() < 1e-10);
        assert!((mid.economy.gini - 0.4).abs() < 1e-10);
        assert!((mid.economy.total_production - 150.0).abs() < 1e-10);
    }

    #[test]
    fn interpolate_at_endpoints() {
        let a = SimSnapshot {
            tick: 5,
            governance: GovernanceSummary {
                stability: 1.0,
                ..Default::default()
            },
            economy: EconomySummary::default(),
            factions: Vec::new(),
            events: Vec::new(),
        };
        let b = SimSnapshot {
            tick: 6,
            governance: GovernanceSummary {
                stability: 0.0,
                ..Default::default()
            },
            economy: EconomySummary::default(),
            factions: Vec::new(),
            events: Vec::new(),
        };

        let at_0 = interpolate_snapshots(&a, &b, 0.0);
        assert!((at_0.governance.stability - 1.0).abs() < 1e-10);

        let at_1 = interpolate_snapshots(&a, &b, 1.0);
        assert!((at_1.governance.stability - 0.0).abs() < 1e-10);
    }
}
