// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial licensing: see COMMERCIAL_LICENSE.md at repository root
//! Thermodynamic enforcement system.
//!
//! Runs at 64Hz in FixedUpdate. Enforces the 7 thermodynamic rules:
//! 1. Moving costs energy
//! 2. Consciousness costs energy
//! 3. Collision spikes prediction error (handled in PhysicsCallback)
//! 4. Harmony resonance transfers energy
//! 5. Sanctuary zones emerge (handled in consciousness coupling)
//! 6. Energy depleted = consciousness collapse
//! 7. Energy regenerates from environment (ambient + wells)
//!
//! FEP-07E splits one simulation tick into an explicit transaction:
//!
//! `thermodynamic_begin_system`
//! → consequential simulation / authoritative physics
//! → `finalize_thermodynamic_tick`
//!
//! Per-tick counters are reset only in the begin phase and sampled only in the
//! finalize phase. This prevents motor/collision work generated by the physics step
//! from being carried into the next ledger interval or erased before HUD telemetry
//! observes it.

use bevy::prelude::*;
use symtropy_physics::BodyHandle;

use crate::components::{CrewNpc, Player};
use crate::resources::{EnergyWell, PhysicsWorldRes, SafetyTier};
use symtropy_render_bridge::PhysicsBody;

/// Marker for entities that have collapsed (zero energy).
#[derive(Component)]
pub struct EnergyCollapsed;

/// Thermodynamic HUD state — accumulates per-tick data for display.
#[derive(Resource, Default)]
pub struct ThermodynamicHudState {
    pub energy_consumed_accumulator: f64,
    pub energy_regenerated_accumulator: f64,
    pub ticks_accumulated: u32,
    /// Per-second rates (updated periodically).
    pub consumed_per_sec: f64,
    pub regenerated_per_sec: f64,
}

/// Begin one thermodynamic simulation transaction.
///
/// This phase owns the **only** per-tick energy-counter reset. It applies costs and
/// environmental flows that must be established before consequential simulation:
/// consciousness maintenance, ambient/well regeneration and epistemic offloading.
///
/// It deliberately does **not** finalize the ledger or sample HUD telemetry. Physics,
/// actuator and collision effects for this fixed tick must still be allowed to write
/// into the same counters before [`finalize_thermodynamic_tick`] closes the interval.
pub fn thermodynamic_begin_system(
    mut physics: ResMut<PhysicsWorldRes>,
    entities_query: Query<(&PhysicsBody, &Transform), Or<(With<Player>, With<CrewNpc>)>>,
    mut wells: Query<(&Transform, &mut EnergyWell, &mut Sprite), Without<Player>>,
) {
    let constants = physics.consciousness.constants.clone();

    // Collect handles and positions for iteration.
    let agent_data: Vec<_> = entities_query
        .iter()
        .map(|(pb, tf)| (pb.handle, tf.translation))
        .collect();
    let handles: Vec<_> = agent_data.iter().map(|(h, _)| *h).collect();

    // Pre-compute values that don't need mutable access.
    let regen_mult = physics.consciousness.resource_regeneration_multiplier();

    // --- Per-entity pre-step flows ---
    for &handle in &handles {
        if let Some(entity) = physics.consciousness.entities.get_mut(&handle) {
            // Reset per-tick counters exactly once, before any tick-N flow.
            entity.energy.tick_reset();

            // Rule 2: Consciousness maintenance cost.
            // Higher Φ costs more: base * (1.0 + phi * 0.5).
            let phi = entity.phi();
            let maintenance = constants.consciousness_maintenance_per_tick * (1.0 + phi * 0.5);
            entity.energy.consume(maintenance);

            // Rule 7: Ambient regeneration (slow, not enough alone).
            let ambient = constants.ambient_regen_rate * regen_mult;
            entity.energy.regenerate(ambient);
        }
    }

    // --- Energy Wells: spatial regeneration sources ---
    for (well_tf, mut well, mut well_sprite) in &mut wells {
        if !well.is_active() {
            well_sprite.color = Color::srgba(0.2, 0.2, 0.2, 0.15); // dim depleted wells
            continue;
        }

        for &(handle, agent_pos) in &agent_data {
            let dist = agent_pos
                .truncate()
                .distance(well_tf.translation.truncate());
            if dist < well.radius {
                let regen = well.regen_rate.min(well.remaining);
                well.remaining -= regen;
                if let Some(entity) = physics.consciousness.entities.get_mut(&handle) {
                    entity.energy.regenerate(regen);
                }
            }
        }

        // Visual: pulse alpha based on remaining capacity.
        let frac = well.fraction_remaining() as f32;
        well_sprite.color = Color::srgba(0.1, 0.8 * frac, 0.6 * frac, 0.2 + 0.3 * frac);
    }

    // Record maintenance consumption as dissipation before consequential simulation.
    // At this point `consumed_this_tick` contains only the pre-step maintenance debit;
    // actuator/collision debits happen later and have their own ledger paths.
    let total_maintenance: f64 = handles
        .iter()
        .filter_map(|h| physics.consciousness.entities.get(h))
        .map(|e| e.energy.consumed_this_tick)
        .sum();
    physics
        .consciousness
        .ledger
        .record_dissipation(total_maintenance);

    // --- Rule 4: Epistemic offloading (resonance REDUCES COSTS, not generates energy) ---
    // Thermodynamically honest: cooperation doesn't create energy.
    // It reduces the prediction error processing cost for nearby agents.
    // When agents resonate, they share internal models via harmony alignment.
    // This means each agent burns fewer Joules on surprise processing.
    //
    // Implementation: resonant agents get their prediction error decayed FASTER
    // and their consciousness maintenance cost REDUCED (not energy added).
    let range = constants.harmony_range;

    for i in 0..handles.len() {
        for j in (i + 1)..handles.len() {
            let ha = handles[i];
            let hb = handles[j];

            let (pos_a, harmonies_a) = {
                let sanctuary_a = physics.consciousness.sanctuaries.get(&ha);
                let entity_a = physics.consciousness.entities.get(&ha);
                match (sanctuary_a, entity_a) {
                    (Some(s), Some(e)) => (s.center, e.harmony_activations),
                    _ => continue,
                }
            };
            let (pos_b, harmonies_b) = {
                let sanctuary_b = physics.consciousness.sanctuaries.get(&hb);
                let entity_b = physics.consciousness.entities.get(&hb);
                match (sanctuary_b, entity_b) {
                    (Some(s), Some(e)) => (s.center, e.harmony_activations),
                    _ => continue,
                }
            };

            let dist = pos_a.distance(&pos_b);
            if dist > range {
                continue;
            }

            let resonance = harmony_resonance(&harmonies_a, &harmonies_b);
            if resonance > 0.5 {
                let offload_factor = (resonance - 0.5) * 2.0; // [0, 1]

                // Epistemic offloading: accelerate prediction error decay
                // (shared models = faster learning = less energy burned on surprise).
                if let Some(entity) = physics.consciousness.entities.get_mut(&ha) {
                    entity.prediction_error *= 1.0 - offload_factor * 0.1; // 10% faster decay per tick
                    entity.motor_precision = 1.0 / (1.0 + entity.prediction_error);
                    // Refund some maintenance cost (predictability reduces processing).
                    entity.energy.regenerate(
                        constants.consciousness_maintenance_per_tick * offload_factor * 0.5,
                    );
                }
                if let Some(entity) = physics.consciousness.entities.get_mut(&hb) {
                    entity.prediction_error *= 1.0 - offload_factor * 0.1;
                    entity.motor_precision = 1.0 / (1.0 + entity.prediction_error);
                    entity.energy.regenerate(
                        constants.consciousness_maintenance_per_tick * offload_factor * 0.5,
                    );
                }

                // Collapse recovery: epistemic offloading can't revive a dead agent
                // but mechanical synergy (being physically carried to an energy well) could.
                // For now: collapsed agents need wells, not friends.
            }
        }
    }

    // Establish the pre-consequence collapse hard stop after all pre-step regeneration
    // opportunities have run. A later in-tick exhaustion is caught again at finalize.
    for &handle in &handles {
        if let Some(entity) = physics.consciousness.entities.get_mut(&handle)
            && entity.energy.is_collapsed()
        {
            entity.safety_tier = SafetyTier::Red;
        }
    }
}

/// Compatibility registration point used by the current plugin.
///
/// FEP-07E intentionally keeps the existing system name so this tranche can close the
/// thermodynamic transaction without rewriting the large shared plugin registration.
/// The later FEP fixed-cadence PR should register [`thermodynamic_begin_system`] by its
/// explicit name and schedule a dedicated finalizer after physics.
pub fn thermodynamic_enforcement_system(
    physics: ResMut<PhysicsWorldRes>,
    entities_query: Query<(&PhysicsBody, &Transform), Or<(With<Player>, With<CrewNpc>)>>,
    wells: Query<(&Transform, &mut EnergyWell, &mut Sprite), Without<Player>>,
) {
    thermodynamic_begin_system(physics, entities_query, wells);
}

/// Close one thermodynamic simulation transaction after all consequential physical
/// effects for the fixed tick have executed.
///
/// This is a plain helper rather than a Bevy system in this compatibility tranche.
/// `physics_sync_transforms` calls it immediately after the authoritative physics step
/// (or at the equivalent fixed boundary in the current kinematic 3D slice). Keeping the
/// logic here makes ownership clear and allows the later schedule rewrite to promote it
/// to a dedicated system without moving accounting semantics again.
pub fn finalize_thermodynamic_tick(
    physics: &mut PhysicsWorldRes,
    hud_state: &mut ThermodynamicHudState,
    handles: &[BodyHandle],
) {
    // Rule 6: catch entities that exhausted their reservoir because of actuator,
    // collision, constraint or other consequence-time costs in this same tick.
    for &handle in handles {
        if let Some(entity) = physics.consciousness.entities.get_mut(&handle)
            && entity.energy.is_collapsed()
        {
            entity.safety_tier = SafetyTier::Red;
        }
    }

    // Finalize exactly once after consequence-time ledger writers have run.
    let _balance = physics.consciousness.tick_thermodynamics();

    // Sample per-tick counters before the next begin phase can reset them.
    hud_state.ticks_accumulated += 1;
    for &handle in handles {
        if let Some(entity) = physics.consciousness.entities.get(&handle) {
            hud_state.energy_consumed_accumulator += entity.energy.consumed_this_tick;
            hud_state.energy_regenerated_accumulator += entity.energy.regenerated_this_tick;
        }
    }

    // Update per-second rates every 16 ticks (~0.25 seconds at 64Hz).
    if hud_state.ticks_accumulated >= 16 {
        let seconds = hud_state.ticks_accumulated as f64 / 64.0;
        hud_state.consumed_per_sec = hud_state.energy_consumed_accumulator / seconds;
        hud_state.regenerated_per_sec = hud_state.energy_regenerated_accumulator / seconds;
        hud_state.energy_consumed_accumulator = 0.0;
        hud_state.energy_regenerated_accumulator = 0.0;
        hud_state.ticks_accumulated = 0;
    }
}

fn harmony_resonance(a: &[f64; 9], b: &[f64; 9]) -> f64 {
    let dot = a.iter().zip(b).map(|(a, b)| a * b).sum::<f64>();
    let mag_a = a.iter().map(|v| v * v).sum::<f64>().sqrt();
    let mag_b = b.iter().map(|v| v * v).sum::<f64>().sqrt();
    if mag_a <= 1e-10 || mag_b <= 1e-10 {
        0.0
    } else {
        (dot / (mag_a * mag_b)).clamp(0.0, 1.0)
    }
}

/// Visual system: gray out collapsed entities. Run in Update.
pub fn collapse_visual_system(
    physics: Res<PhysicsWorldRes>,
    mut commands: Commands,
    mut query: Query<(
        Entity,
        &PhysicsBody,
        Option<&mut Sprite>,
        Option<&MeshMaterial3d<StandardMaterial>>,
        Option<&EnergyCollapsed>,
    )>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    for (entity, body_comp, opt_sprite, opt_mat, collapsed_marker) in &mut query {
        let is_collapsed = physics
            .consciousness
            .entities
            .get(&body_comp.handle)
            .map(|e| e.energy.is_collapsed())
            .unwrap_or(false);

        if is_collapsed && collapsed_marker.is_none() {
            if let Some(mut sprite) = opt_sprite {
                sprite.color = Color::srgba(0.3, 0.3, 0.3, 0.7);
            }
            if let Some(mat_handle) = opt_mat
                && let Some(mut mat) = materials.get_mut(&mat_handle.0)
            {
                mat.base_color = Color::srgba(0.3, 0.3, 0.3, 0.7);
            }
            commands.entity(entity).insert(EnergyCollapsed);
        } else if !is_collapsed && collapsed_marker.is_some() {
            if let Some(mut sprite) = opt_sprite {
                sprite.color = Color::srgba(1.0, 1.0, 1.0, 1.0);
            }
            if let Some(mat_handle) = opt_mat
                && let Some(mut mat) = materials.get_mut(&mat_handle.0)
            {
                mat.base_color = Color::srgba(1.0, 1.0, 1.0, 1.0);
            }
            commands.entity(entity).remove::<EnergyCollapsed>();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn registered_agent(energy: f64) -> (PhysicsWorldRes, BodyHandle) {
        let mut physics = PhysicsWorldRes::default();
        let handle = physics
            .world
            .add_sphere(symtropy_math::Point::origin(), 1.0, 1.0);
        physics.consciousness.register(handle, energy, 10.0);
        (physics, handle)
    }

    #[test]
    fn finalize_samples_consequence_time_energy_before_next_reset() {
        let (mut physics, handle) = registered_agent(100.0);
        let entity = physics.consciousness.entities.get_mut(&handle).unwrap();
        entity.energy.tick_reset();
        let _ = entity.energy.consume(5.0);

        let mut hud = ThermodynamicHudState::default();
        finalize_thermodynamic_tick(&mut physics, &mut hud, &[handle]);

        assert_eq!(hud.ticks_accumulated, 1);
        assert!((hud.energy_consumed_accumulator - 5.0).abs() < 1e-9);
    }

    #[test]
    fn finalize_marks_newly_exhausted_entity_red() {
        let (mut physics, handle) = registered_agent(1.0);
        {
            let entity = physics.consciousness.entities.get_mut(&handle).unwrap();
            entity.energy.tick_reset();
            let _ = entity.energy.consume(1.0);
            entity.safety_tier = SafetyTier::Green;
        }

        let mut hud = ThermodynamicHudState::default();
        finalize_thermodynamic_tick(&mut physics, &mut hud, &[handle]);

        let entity = physics.consciousness.entities.get(&handle).unwrap();
        assert!(entity.energy.is_collapsed());
        assert_eq!(entity.safety_tier, SafetyTier::Red);
    }
}
