// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Holographic Reflex: Direct mapping from SpacetimeCrystalField to actuators.

use bevy::prelude::*;
use nalgebra::Vector3;
use symtropy_core_stable::spacetime::SpacetimeCrystalField;

/// The Reflex bridge component: forces generated by local crystal gradient.
#[derive(Component)]
pub struct HolographicReflex {
    pub gain: f32,
    pub torque_scale: f32,
}

impl Default for HolographicReflex {
    fn default() -> Self {
        Self {
            gain: 1.0,
            torque_scale: 1e5,
        }
    }
}

/// System that probes the local gravitational gradient and applies torque.
pub fn holographic_reflex_system(
    crystal: Res<crate::celestial::CrystalFieldResource>,
    mut query: Query<(&Transform, &mut HolographicReflex)>,
) {
    let epsilon = 0.01;
    for (transform, reflex) in query.iter_mut() {
        let pos = Vector3::new(
            transform.translation.x as f64,
            transform.translation.y as f64,
            transform.translation.z as f64,
        );

        // Compute gradient of the potential field
        let p = crystal.field.probe(pos);
        let grad = Vector3::new(
            crystal.field.probe(pos + Vector3::x() * epsilon) - p,
            crystal.field.probe(pos + Vector3::y() * epsilon) - p,
            crystal.field.probe(pos + Vector3::z() * epsilon) - p,
        ) / epsilon as f32;

        // Mapping gradient to torque (reflexive orientation)
        let torque = Vec3::new(grad.x as f32, grad.y as f32, grad.z as f32)
            * reflex.torque_scale
            * reflex.gain;

        // Actuate: in a real physics world, this would apply to the RigidBody
        // Here, we modulate the attitude (visual proxy for reflex)
        // spacecraft.attitude = spacecraft.attitude.lerp(target, gain * dt);
        debug!("Reflex torque: {:?}", torque);
    }
}
